### ISSUE TITLE
Proxy handling of Connection ID resuse

### ISSUE THREAD

**Issue by LPardue** [tfpauly/quic-proxy#17]
So the spec says:

> For any non-zero-length Client Connection ID, the Connection ID MUST be unique
across all other clients.

What does a proxy do if it detects this is not the case? The logical thing seems to be to fail fast, reject the 2nd CONNECT-QUIC that attempts to reuse an ID already taken. Not sure of a status code - 409 maybe?

**Comment by tfpauly** [comment]
Addressed by #24
