### ISSUE TITLE
Reusing DATAGRAM Flow IDs

### ISSUE THREAD

**Issue by DavidSchinazi** [tfpauly/quic-proxy#20]
In the Example section, the spec reuses the same Flow ID for two separate CONNECT-QUIC requests. That seems like a reasonable choice to me, but the spec should explicitly call out that this is allowed, and that the proxy should validate that upon receiving a new CONNECT-UDP request that reuses a flow ID, the authority must match the authority of the first CONNECT-QUIC request that used the same flow ID.

**Comment by tfpauly** [comment]
Agreed, good to clarify.

**Comment by tfpauly** [comment]
Agreed, good to clarify.

**Comment by tfpauly** [comment]
Addressed by #24
