### ISSUE TITLE
Mapping details don't seem right

### ISSUE THREAD

**Issue by DavidSchinazi** [tfpauly/quic-proxy#21]
The only details about how mappings work seem to be this part of the "Proxy Response Behavior" section:
> Creating a mapping entry for the QUIC Connection ID in the given direction (client or target server) associated with the client's IP address and UDP port. For any non-zero-length Client Connection ID, the Connection ID MUST be unique across all other clients.

That's not right. You need at least the following mappings:
- from flow ID to target IP/port (for tunneling)
- from Server Connection ID to target IP/port (for forwarding)
- from target IP/port to (QUIC connection, flow ID) (for tunneling)
- from target IP/port to client IP/port (for forwarding)

**Comment by tfpauly** [comment]
Addressed by #24
