### ISSUE TITLE
Is the concept of a "Client Connection ID" needed?

### ISSUE THREAD

**Issue by DavidSchinazi** [tfpauly/quic-proxy#22]
The document mentions the concept of a "Client Connection ID", but I'm not sure they serve any purpose.

For example:
> Clients SHOULD establish mappings for any Client Connection ID values it provides to the destination target. Failure to do so will prevent the target from initiating connection migration probes along new paths.

What is the Client Connection ID mapped *to*? (see #21 about clarifying that)

If you create one UDP socket per CONNECT-QUIC request, then you don't need the concept of a Client Connection ID. The server knows how to route packets simply based on the UDP socket they came in on.

The draft mentions validating that a Client Connection ID has been properly registered before allowing its use, but I don't see what benefit that provides.

I feel like this concept might have been inherited from [the original MASQUE QUIC Proxying](https://tools.ietf.org/html/draft-schinazi-masque-protocol-01#section-3.3) but there it was needed to allow the MASQUE server to only use one UDP port, which isn't a requirement here. Am I missing something?

**Comment by tfpauly** [comment]
Addressed by #24
