### ISSUE TITLE
Include details about proxy connection ID mappings

### ISSUE THREAD

**Issue by tfpauly** [tfpauly/quic-proxy#3]
From @DavidSchinazi 

The issue about connection ID lengths should be addressed: since the end-server decides its own connection IDs, the client and proxy have no control over Server-Connection-Id. If the client sends non-tunneled short header packets, the server won't be able to figure out the connection ID length. The server could try all possible values, but either way I think this should be mentioned in the draft. In particular, the end of the Load Balancer seems to ignore this problem - the proxy's load balancer won't be collaborating with the end-server so I think this is broken

Beyond this, we can talk about how the proxy can try to re-use a socket between itself and the target, but that it needs to detect cases when a Connection ID cannot be distinguished (due to overlap in part, or insufficient length), and either create a new socket, or fail the request.

**Comment by DavidSchinazi** [comment]
I think that we can close this issue in favor of #21 and #22. I tried to explain my thoughts there better than I had in the email that led to opening this issue...

**Comment by tfpauly** [comment]
Sounds good to me!
