### ISSUE TITLE
Provide advice about initial MSS of QUIC connections to proxies

### ISSUE THREAD

**Issue by tfpauly** [tfpauly/quic-proxy#33]
Rather that just using 1200 bytes, QUIC connections to proxies should add extra bytes to account for proxied QUIC connections that will themselves send initial packets of 1200 bytes that will need to fit in DATAGRAM frames.

**Comment by DavidSchinazi** [comment]
Can you elaborate please? Where would extra bytes be added?

**Comment by tfpauly** [comment]
Say you know you want to proxy QUIC over QUIC. You know that your proxied QUIC connection will need to send a QUIC initial of 1200 bytes. This means you need to be able to send at least 1200-byte DATAGRAM frames.

If the QUIC connection to the proxy starts with an MSS of 1200 bytes, you either need to ramp up your effective MSS enough to handle larger frames (such as via path MTU discovery, or just bumping it up optimistically), or you choose a slightly larger initial packet size. Choosing a larger packet size also has the nice benefit of ensuring that the path can actually handle your traffic without risking finding out later it won't work.

I'm saying we should have text around this topic, and it seems simple to recommend that clients choose a slightly larger initial packet size to the proxy.

**Comment by DavidSchinazi** [comment]
Thanks, I understand. Our implementation uses a MSS of 1350 and falls back to TCP if that doesn't go through. Adding text to suggest that or PMTUD sounds good to me.
