### ISSUE TITLE
Links no longer working regarding the "connect" WG

### ISSUE THREAD

**Issue by starrify** [tfpauly/quic-proxy#56]
(Sorry in advance for this potentially stupid ticket. :sweat_smile:)

I happen to notice that these three links are not working: 
https://github.com/tfpauly/quic-proxy/blob/ad94640114f279624009dc17873953d7fde42f42/CONTRIBUTING.md?plain=1#L20-L31

It looks a little bit weird because there seems to be no working group called "connect" from [the current list](https://datatracker.ietf.org/wg/) and [the historical list](https://datatracker.ietf.org/group/concluded/).

**Comment by tfpauly** [comment]
Weird, I think some automated setup did that wrong! I'll fix it.

**Comment by tfpauly** [comment]
Fixed to point to masque.
