### ISSUE TITLE
Are there potentially no ACKs? What then?

### ISSUE THREAD

**Issue by martinduke** [tfpauly/quic-proxy#69]
Forwarding mode, of course, doesn't have packet numbers for the outer connection. If there's nothing else going over the outer connection, it is therefore impractical for the proxy to send ACKs. So what are the implications for congestion control, idle timeouts, and so on?

Frequent ACKs in response to QUIC packets are pretty fundamental to congestion control, timeouts, and perhaps other transport layer mechanisms, and we ought to think through the implications of fully relying on the inner connection for all of those functions.

**Comment by DavidSchinazi** [comment]
That's a good point, if we're exclusively using forwarding mode the outer QUIC connection could succumb to an idle timeout. It's pretty easy to avoid that by periodically sending PING frames, I'd suggest we mention this to warn implementers.

**Comment by tfpauly** [comment]
Yeah in practice we have periodic pings to the proxy that’s in forwarding mode.
